# Generated by Django 5.0.1 on 2024-01-17 06:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remaining_payment',
            field=models.FloatField(blank=True, default=121111212),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='payment_installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('payment_entry', models.FloatField(default=0)),
                ('paid_date', models.DateField(default=datetime.datetime(2024, 1, 17, 6, 39, 22, 369002, tzinfo=datetime.timezone.utc))),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
